### ISSUE TITLE
소스코드 make 오류

### ISSUE THREAD

**Issue by leejseo** [SungjoonPark/KoreanWordVectors#1]
README.md에 적힌 바와 같이
```
cd src
make
```
를 했을 때 `recipe for target 'fasttext' failed` 라는 오류가 생깁니다.
혹시 소스코드를 빌드할 때 기존에 설치되어 있는 fasttext를 지우고 빌드해야 하는지 궁금하여 질문드립니다.

감사합니다.

이종서 드림.

**Comment by SungjoonPark** [comment]
네 기존에 이미 컴파일된 소스들은 지우고 새로 빌드하셔야 하는 것은 맞습니다. 다만 말씀하신 오류가 그것 때문인지는 잘 모르겠습니다 ㅠㅠ

2020년 7월 9일 (목) 오전 11:32, Jongseo Lee <notifications@github.com>님이 작성:
