### ISSUE TITLE
make 오류

### ISSUE THREAD

**Issue by TransAmRaiser** [SungjoonPark/KoreanWordVectors#2]
안녕하세요. 
이전에 Issue로 등록되어 있었던 사항입니다만, 저 역시 같은 오류를 겪어서 제보합니다.

make를 하면 오류가 발생하여 사용할 수가 없습니다.
총 네 환경에서 테스트해 보았습니다만 모두 실패했습니다.

우선 이것저것 깔려 있는 게 많은 mac OS 10.15.6과 Ubuntu 16.04 환경에서는 다음과 같은 오류 메시지가 뜹니다.
![image](https://user-images.githubusercontent.com/39158768/95194147-e554be80-080f-11eb-9966-583d4510a801.png)
참고로 mac OS에는 fasttext를 설치한 적이 없고, Ubuntu에는 fasttext 0.9.2가 이미 설치되어 있는 상태입니다.

설치 후 별다른 작업을 하지 않은 Ubuntu 16.04 두 환경(하나는 일반 PC, 하나는 가상머신)에서는 다음과 같은 오류 메시지가 뜹니다.
![image](https://user-images.githubusercontent.com/39158768/95194990-ec300100-0810-11eb-9f80-03154d571e92.png)

포기하고 자소 분해 파이썬 파일만 이용을 하려 했으나, 원본 fasttext에서 수정하신 부분이 있는 듯하여 github 문서에 있는 파라미터들을 넣으면 원본 fasttext에서는 작동이 불가하더군요.

이미 한 번 제보가 있기도 하였고 아마 저 말고도 많은 분들이 문제를 겪었을 것으로 생각이 되는데, 해결책을 제시해 주시면 감사하겠습니다.

**Comment by taeheejeon22** [comment]
```bash
make clean
make opt
```
자세한 사정은 모르겠으나, 이렇게 하면 됩니다.

https://github.com/facebookresearch/fastText/issues/231
